//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARKING()
        {
            this.RENT = new HashSet<RENT>();
        }
    
        public short ID { get; set; }
        public short USER_ID { get; set; }
        public string ADRESS { get; set; }
        public double PAY_PER_HOUR { get; set; }
        public double LAT { get; set; }
        public double LAN { get; set; }
        public Nullable<bool> ELECTRONIC_GATE { get; set; }
        public Nullable<bool> INDOOR { get; set; }
        public Nullable<bool> SHADY { get; set; }
        public string SIZE_FOR { get; set; }
        public Nullable<short> CANCEL_TIME { get; set; }
        public string NOTES { get; set; }
        public string IMG1 { get; set; }
        public string IMG2 { get; set; }
        public string IMG3 { get; set; }
        public Nullable<short> ACCOUNT_ID { get; set; }
    
        public virtual BANK_ACCOUNT BANK_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENT> RENT { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
