//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINT
    {
        public short ID { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public short PARKING_ID { get; set; }
    
        public virtual PARKING PARKING { get; set; }
    }
}
