//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENT
    {
        public short ID { get; set; }
        public short USER_ID { get; set; }
        public short PARKING_ID { get; set; }
        public System.DateTime ENTRY_HOUR { get; set; }
        public System.DateTime LEAVING_HOUR { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public System.DateTime LEAVING_DATE { get; set; }
    
        public virtual PARKING PARKING { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
